### ISSUE TITLE
invalid operands to binary expression

### ISSUE THREAD

**Issue by douyw** [aminroosta/sqlite_modern_cpp#13]
I pulled the latest source code, still no luck. I use Qt5.4.1 on OSX10.10.
The test code is still from README file.
The source code:
```c++
         db << "insert into user (age,name,weight) values (?,?,?);"
             << 20      // <-- here is the error line indicated by QtCreator.
             << u"bob" // utf16 string
             << 83.25f;
```
The compiling errors:
```
../UseSqlModernCpp/util.cpp:40:14: error: invalid operands to binary expression ('sqlite::database_binder' and 'int')
             << 20
             ^  ~~
../UseSqlModernCpp/sqlite_modern_cpp.h:258:29: note: candidate function [with T = int] not viable: expects an l-value for 1st argument
template<> database_binder& operator <<(database_binder& db, const int& val) {
                            ^
../UseSqlModernCpp/util.cpp:45:14: error: invalid operands to binary expression ('sqlite::database_binder' and 'int')
             << 21
             ^  ~~
../UseSqlModernCpp/sqlite_modern_cpp.h:258:29: note: candidate function [with T = int] not viable: expects an l-value for 1st argument
template<> database_binder& operator <<(database_binder& db, const int& val) {
                            ^
../UseSqlModernCpp/util.cpp:54:14: error: invalid operands to binary expression ('sqlite::database_binder' and 'int')
             << 18
             ^  ~~
../UseSqlModernCpp/sqlite_modern_cpp.h:258:29: note: candidate function [with T = int] not viable: expects an l-value for 1st argument
template<> database_binder& operator <<(database_binder& db, const int& val) {
                            ^
3 errors generated.
make: *** [util.o] Error 1
14:20:12: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project UseSqlModernCpp (kit: Desktop Qt 5.4.1 clang 64bit)
```
There are many other warnings, I eliminated them via removing 'using namespace ' lines. It seems that database_binder's operator<< is mixed (or polluted) with std::ostream's operator<< each other when "using namespace" lines are used.

**Comment by Killili** [comment]
Hm, looks like youre compiler will not pass a const reference from a constant(rvalue), he is expecting a variable(lvalue) instead.
Changing the constant "20" to a variable should fix that.
Or even better write youre constants into the SQL.
`db << "insert into user (age,name,weight) values (20,'bob',83.25);";`

**Comment by Killili** [comment]
Reopen this if the issue is still present.

**Comment by wttw** [comment]
Same issue here, I'm afraid. It's not Qt related, and binding a variable rather than a constant doesn't fix it.

OS X 10.10, Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)

Test case:
```
#include "src/sqlite_modern_cpp.h"

int main()
{

  sqlite::database db("dbfile.db");

  int foo = 42;
  db << "insert into user (age) values (?);"
     << foo;
}
```
Command line and errors:
```
~/sqlite_modern_cpp ∙ g++ -std=c++11 test.cc -o test.o
test.cc:10:6: error: invalid operands to binary expression ('sqlite::database_binder'
      and 'int')
     << foo;
     ^  ~~~
./src/sqlite_modern_cpp.h:258:29: note: candidate function [with T = int] not viable:
      expects an l-value for 1st argument
template<> database_binder& operator <<(database_binder& db, const int& val) {
                            ^
1 error generated.
```

**Comment by Killili** [comment]
Hm, i have no easy way to test that compiler right now. But there is the "beta" version of a new iteration of this lib in my fork. It will eventually become the next version and has a different way to deal with the stream operators maybe that will fix it, for you. It still looks like a misunderstanding of either us or the LLVM compiler on how to treat the stream arguments.

https://github.com/Killili/sqlite_modern_cpp

**Comment by wttw** [comment]
Still the same issue with that code.

I'm playing with it now; I'll leave a note if I find anything.

**Comment by aminroosta** [comment]
Can you Test the Fix13 branch ?
I have overloaded rvalue references as well.

**Comment by bbouzan** [comment]
Hello, I have the exact same problem. Tried the master branch and Fix 13. Same problem.
I'm using gcc for arm-linux.

**Comment by unphased** [comment]
Can confirm the problem on master branch with `g++ (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)`

**Comment by unphased** [comment]
Any update? This is somewhat of a problem if you want to call this project "modern" :sweat_smile: Neither clang nor g++ are happy even when I am using variables to construct the query. 

Assembling the query as a raw string with C++ is a "workaround" but far, far from ideal.

**Comment by aminroosta** [comment]
You are absoluely right.


There is no point in having a good library in you are not going to support it!


I'm installing a linux VM, that way i can test this on clang and g++.


 I will fix this soon.





On Sat, Sep 26, 2015 at 1:56 PM -0700, "Steven Lu" <notifications@github.com> wrote:
Any update? This is somewhat of a problem if you want to call this project "modern" :sweat_smile: Neither clang nor g++ are happy even when I am using variables to construct the query.

Assembling the query as a raw string with C++ is a "workaround" but far, far from ideal.

---

**Comment by aminroosta** [comment]
based on @unphased  workaround, i think there is something wrong with **rvalue** references.
```c++
// line 94
//instead of 
template<typename T> friend database_binder& operator <<(database_binder& ddb, const T& val);
// we should write
template<typename T> friend database_binder& operator <<(database_binder&& ddb, const T& val);
//and overload `<<` operator for `database_binder&&`.
```

I have tested the above changes and the compiler (g++-4.8) doesn't complain about `<<` operator any more.
BUT the linker gives me this error:
`undefined reference to `sqlite::database_binder& sqlite::operator<< <double>(sqlite::database_binder&, double const&)'`

I will dig more into this,
Any help will be appreciated :)

**Comment by Killili** [comment]
I did try something similar, but i think we chase the wrong bug. Its not in the way the API works its just how we describe it to the compiler and changing the ref to something else will change the behavior. 

Clearly the ref method is needed because the compiler instantiates it but does not add code because all we define is code for rvalue refs then. And its the same way around in its current form. All i can think of is adding both but cant test that right now. And i have no clue why we should have both, thats what bothers me.

**Comment by aminroosta** [comment]
I should probably keep this issue open, 
I have only tested this on g++-4.8.

It's been a long day with `lots of try and errors` !

**TODO:**
check this on clang and visual c++.
fix "extensions/boost_optional.h".

**Comment by unphased** [comment]
@aminroosta I would like to make a note (mostly to myself!) that my "hack" that i proposed making a temporary variable for the database binder object and referencing it while feeding values in causes the updated code since a28db4a to fail to compile. 

So probably we have a series of lvalue reference `operator <<` overload bits to put in to make that also work again.

**Comment by Killili** [comment]
We have a working version for VS2015, g++ 4.8/5.2 and clang 7.0.2 with V2 so i guess we can close this now.
